services:
    taskmaster:
        image: ${DOCKER_REGISTRY-}taskmaster
        build:
            context: .
            dockerfile: TaskMaster.WebApi/Dockerfile 
        ports:
            - "8079:8080"
        depends_on:
            - sqldata

    sqldata:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - MSSQL_SA_PASSWORD=Teste#1234
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433" 